################# 数据库配置 #################
database:
  tyfund:
      read:
        url: jdbc:mysql://192.168.51.121:3306/tyfund_user?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: abc123456@@..
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
      write:
        url: jdbc:mysql://192.168.51.121:3306/tyfund_user?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: abc123456@@..
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
################# druid数据源 #################
druid:
  pool:
    initialSize: 10
    maxActive: 100
    minIdle: 10
################# 非关系型数据库配置 #################
nosql:
  redis:
    tyfund:
      database: 8
      password: gxja@2019
      sentinel:
        master: master
        nodes: '192.168.51.21:26379,192.168.51.22:26379,192.168.51.23:26379'
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0

################# 短信接口 #################
sms:
  # 同一手机号一天最多发送次数
  dayMaxCount: 500
  # 同一手机号发送短信间隔时间
  intervalSecond: 60
  # 测试模式
  test: true

hystrix:
  command.default.execution.isolation.thread.timeoutInMilliseconds: 8000
  threadpool.default.coreSize: 20
  
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048

mybatis:
  configuration:
    map-underscore-to-camelCase: true
  mapper-locations: "classpath*:mappers/**/*.xml"

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.tuaidai.funds.model.entity
  global-config:
    id-type: 3
    field-strategy: 2
    auto-set-db-type: true
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# Discovery Server Access
eureka:
  instance:
    # hostname: localhost
    preferIpAddress: true
  client:
    registryFetchIntervalSeconds: 10
    instanceInfoReplicationIntervalSeconds: 10
    initialInstanceInfoReplicationIntervalSeconds: 20
    registerWithEureka: true
    fetchRegistry: true

#短信平台服务
sms-service:
  verify:
    appId: 36
    key: trrs3333
    templateId: 6
  sale:
    appId: 38
    key: trrs3333
    templateId: 2
  notify:
    appId: 40
    key: trrs3333
    templateId: 4

#tmm事务配置
spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: adc
        password: 123
        virtual-host: "/tyfund_tmm"
        listener:
          default-requeue-rejected: false
          retry:
            enabled: true
            initial-interval: 2000
            max-attempts: 3
            multiplier: 2
            max-interval: 5000
        tmm.producer.enabled: true
    tmmService:
       rpcPath: /data/tmm/tyfund-user-service
       batch:
         size: 2000
       check:
         interval:
           time: 10000
       monitor:
         interval:
           time: 10000

##xxl-job配置
xxl:
  job:
    admin:
      addresses: http://localhost:8080/xxl-job-admin
    executor:
      appname: tyfund-user-service
      ip:
      port: 33333
      logpath: /data/logs/tyfund-user-service/jobhandler
    accessToken:
    

#性能日志配置
app.performance.log.ignore.urlParams: /user/**,/smsLog/**,/sms/**

tyfund:
  exchange:
    monitor: tyfund_exchange_monitor_test
