ufx:
  #机构号
  compId: 50056
  baseUrl: https://sandbox.hscloud.cn
  protocol: http
  oauth:
    grantType: client_credentials
    clientType:aa
    apiKey: 2fea9812-9df6-473d-b270-29c4852d168f
    apiSecret: 45e01565-209f-42ac-ae6e-5d985f4dbe37
    accessTokenUrl: https://sandbox.hscloud.cn/oauth2/oauth2/token
    authorizeUrl: https://sandbox.hscloud.cn/oauth2/oauth2/authorize
    #距离accessToken过期前重新获取 (单位 s)
    reGainAccessTokenTime: 1800
  http:
    maxConnectTime: 20000
    maxSocketTime: 50000
    maxRequestConnectTime: -1
    maxTotalConnect: 10
    maxConnPerRoute: 2

hystrix:
  command.default.execution.isolation.thread.timeoutInMilliseconds: 15000
  threadpool.default.coreSize: 20
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
ribbon:
  # 默认的连接超时时间, Feign会优先读取这个配置
  ConnectTimeout: 20000
  # 默认的读取超时时间,  Feign会优先读取这个配置
  ReadTimeout: 20000

# Discovery Server Access
eureka:
  instance:
    preferIpAddress: true
  client:
    registryFetchIntervalSeconds: 10
    instanceInfoReplicationIntervalSeconds: 10
    initialInstanceInfoReplicationIntervalSeconds: 20
    registerWithEureka: true
    fetchRegistry: true
    
tyfund:
  config:
    capitalMode: M      # 支付渠道 通联支付
    merchantName: HYHX  # 商户名称， 华奕恒信
    taNo: C4  # 默认TA编号
  monitor:
    enabled: true
  exchange:
    monitor: tyfund_exchange_monitor_test
    trade: tyfund_exchange_trade_test123
  queue:        
    allot_req: tyfund_queue_allot_req_test
    redeem_req: tyfund_queue_redeem_req_test
    allot_resp: tyfund_queue_allot_resp_test
    redeem_resp: tyfund_queue_redeem_resp_test
  route:
    allot_req: tyfund_route_allot_req_test
    redeem_req: tyfund_route_redeem_req_test
    allot_resp: tyfund_route_allot_resp_test
    redeem_resp: tyfund_route_redeem_resp_test

#tmm事务配置
spring:
    rabbitmq:
        host: "10.100.11.73"
        port: 5672
        username: "tyfund"
        password: "tyfund"
        virtual-host: "/tyfund_tmm"
        listener:
          default-requeue-rejected: false
          retry:
            enabled: true
            initial-interval: 1000
            max-attempts: 3
            multiplier: 2
            max-interval: 3000
        tmm.producer.enabled: true
    tmmService:
       rpcPath: /data/tmm/tyfund-hscloud-service
       batch:
         size: 2000
       check:
         interval:
           time: 10000
       monitor:
         interval:
           time: 10000
