################# 数据库配置 #################
database:
  tyfund:
      read:
        url: jdbc:mysql://10.100.14.54:3306/test_tyfund_admin?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: tyfund_read
        password: 2FhYE9fIAFP1P#Tk
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
      write:
        url: jdbc:mysql://10.100.14.54:3306/test_tyfund_admin?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: tyfund_write
        password: 2FhYE9fIAFP1P#Tk
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
################# druid数据源 #################
druid:
  pool:
    initialSize: 10
    maxActive: 100
    minIdle: 10

################# 非关系型数据库配置 #################
nosql:
  redis:
    tyfund:
      database: 8
      password: test
      sentinel:
        master: my_master
        nodes: 'node.td-k8s.com:22379'
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0

spring:
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    # 指定静态资源的路径
    resources:
        static-locations: classpath:/static/,classpath:/views/
    # tmm事务配置
    rabbitmq:
        host: "10.100.11.73"
        port: 5672
        username: "tyfund"
        password: "tyfund"
        virtual-host: "/tyfund_tmm"
        listener:
          default-requeue-rejected: false
          retry:
            enabled: true
            initial-interval: 2000
            max-attempts: 3
            multiplier: 2
            max-interval: 5000
        tmm.producer.enabled: true
    tmmService:
       rpcPath: /data/tmm/tyfund-web-admin
       batch:
         size: 2000
       check:
         interval:
           time: 10000
       monitor:
         interval:
           time: 10000

tyfund:
    monitor:
       enabled: true
    event:
       waitSecond: 5
    exchange:
       monitor: tyfund_exchange_monitor_test
       event: tyfund_exchange_event_test
    queue:
       monitor: tyfund_queue_monitor_test
       event: tyfund_queue_event_test

tuandai:
  globals:
    fileDomain: "http://static.tyfund.com/upload"
    picStoreRootPath: "/data/upload/"
    upload-dir-prefix: "ueditor/file/"
    webHost: "http://www.tyfund.com"
    haltMachineUrl: "http://localhost:8081/tdmonitor/haltMachine/use/"
    systemRepairKey: "halt_assert"
    upload-api: "https://upload.tyfund.com/upload/base64"
    upload-oss: "http://10.100.14.40:58015/aliyun/oss/downloadZipUpload"
